databases:
  - name: coredb
    plan: free
    databaseName: core
    user: core

services:
  - type: web
    plan: free
    name: core
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m uvicorn core.asgi:application --workers 4'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coredb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4